<?xml version="1.0" ?>
<testsuite errors="4" failures="0" name="CheckOpiFormat-20171122132341" tests="7" time="0.000">
	<testcase classname="CheckOpiFormat" name="test_GIVEN_a_label_THEN_it_ends_in_a_colon" time="0.000"/>
	<testcase classname="CheckOpiFormat" name="test_GIVEN_an_opi_file_with_grouping_containers_WHEN_checking_the_background_colour_THEN_it_is_the_isis_background" time="0.000"/>
	<testcase classname="CheckOpiFormat" name="test_GIVEN_an_opi_file_with_labels_WHEN_checking_the_background_colour_THEN_it_is_the_isis_background" time="0.000"/>
	<testcase classname="CheckOpiFormat" name="test_GIVEN_an_opi_file_with_led_WHEN_checking_off_colour_THEN_it_is_the_isis_led_off_colour" time="0.000">
		<error message="On line 908, text 'LED', colour was not correct." type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "check_opi_format.py", line 313, in test_GIVEN_an_opi_file_with_led_WHEN_checking_off_colour_THEN_it_is_the_isis_led_off_colour
    self._assert_colour_correct("off_color", "LED", ["ISIS_Green_LED_Off", "ISIS_Red_LED_Off"])
  File "check_opi_format.py", line 295, in _assert_colour_correct
    self.fail("\n".join(["On line {}, text '{}', colour was not correct.".format(*error) for error in errors]))
AssertionError: On line 908, text 'LED', colour was not correct.
]]>		</error>
	</testcase>
	<testcase classname="CheckOpiFormat" name="test_GIVEN_an_opi_file_with_led_WHEN_checking_on_colour_THEN_it_is_the_isis_led_on_colour" time="0.000">
		<error message="On line 888, text 'LED', colour was not correct." type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "check_opi_format.py", line 310, in test_GIVEN_an_opi_file_with_led_WHEN_checking_on_colour_THEN_it_is_the_isis_led_on_colour
    self._assert_colour_correct("on_color", "LED", ["ISIS_Green_LED_On", "ISIS_Red_LED_On"])
  File "check_opi_format.py", line 295, in _assert_colour_correct
    self.fail("\n".join(["On line {}, text '{}', colour was not correct.".format(*error) for error in errors]))
AssertionError: On line 888, text 'LED', colour was not correct.
]]>		</error>
	</testcase>
	<testcase classname="CheckOpiFormat" name="test_GIVEN_an_opi_file_with_textbox_WHEN_checking_background_colour_THEN_it_is_the_isis_textbox_background" time="0.000">
		<error message="On line 771, text 'None', colour was not correct.
On line 1013, text 'None', colour was not correct.
On line 1324, text 'None', colour was not correct.
On line 1523, text 'None', colour was not correct." type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "check_opi_format.py", line 304, in test_GIVEN_an_opi_file_with_textbox_WHEN_checking_background_colour_THEN_it_is_the_isis_textbox_background
    self._assert_colour_correct("background_color", "TextInput", ["ISIS_Textbox_Background"])
  File "check_opi_format.py", line 295, in _assert_colour_correct
    self.fail("\n".join(["On line {}, text '{}', colour was not correct.".format(*error) for error in errors]))
AssertionError: On line 771, text 'None', colour was not correct.
On line 1013, text 'None', colour was not correct.
On line 1324, text 'None', colour was not correct.
On line 1523, text 'None', colour was not correct.
]]>		</error>
	</testcase>
	<testcase classname="CheckOpiFormat" name="test_GIVEN_an_opi_file_with_textbox_WHEN_checking_foreground_colour_THEN_it_is_the_isis_textbox_foreground" time="0.000">
		<error message="On line 778, text 'None', colour was not correct.
On line 1020, text 'None', colour was not correct.
On line 1331, text 'None', colour was not correct.
On line 1530, text 'None', colour was not correct." type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "check_opi_format.py", line 307, in test_GIVEN_an_opi_file_with_textbox_WHEN_checking_foreground_colour_THEN_it_is_the_isis_textbox_foreground
    self._assert_colour_correct("foreground_color", "TextInput", ["ISIS_Standard_Text"])
  File "check_opi_format.py", line 295, in _assert_colour_correct
    self.fail("\n".join(["On line {}, text '{}', colour was not correct.".format(*error) for error in errors]))
AssertionError: On line 778, text 'None', colour was not correct.
On line 1020, text 'None', colour was not correct.
On line 1331, text 'None', colour was not correct.
On line 1530, text 'None', colour was not correct.
]]>		</error>
	</testcase>
	<system-out>
<![CDATA[]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
