<?xml version="1.0" ?>
<testsuite errors="5" failures="0" name="CheckOpiFormat-20180521105103" tests="16" time="0.016">
	<testcase classname="CheckOpiFormat" name="test_GIVEN_a_LED_THEN_it_is_within_a_grouping_container" time="0.000"/>
	<testcase classname="CheckOpiFormat" name="test_GIVEN_a_TextInput_THEN_it_is_within_a_grouping_container" time="0.000"/>
	<testcase classname="CheckOpiFormat" name="test_GIVEN_a_combo_THEN_it_is_within_a_grouping_container" time="0.000"/>
	<testcase classname="CheckOpiFormat" name="test_GIVEN_a_label_THEN_it_has_correct_font" time="0.000"/>
	<testcase classname="CheckOpiFormat" name="test_GIVEN_a_label_outside_a_grouping_container_THEN_it_is_title_case" time="0.000"/>
	<testcase classname="CheckOpiFormat" name="test_GIVEN_a_push_button_THEN_it_is_within_a_grouping_container" time="0.000"/>
	<testcase classname="CheckOpiFormat" name="test_GIVEN_an_opi_file_with_graph_widgets_WHEN_checking_buffer_sizes_THEN_all_buffer_sizes_are_the_same" time="0.000"/>
	<testcase classname="CheckOpiFormat" name="test_GIVEN_an_opi_file_with_labels_WHEN_checking_the_background_colour_THEN_it_is_the_isis_background" time="0.000"/>
	<testcase classname="CheckOpiFormat" name="test_GIVEN_an_opi_file_with_textbox_WHEN_checking_background_colour_THEN_it_is_the_isis_textbox_background" time="0.000"/>
	<testcase classname="CheckOpiFormat" name="test_GIVEN_an_opi_file_with_textbox_WHEN_checking_foreground_colour_THEN_it_is_the_isis_textbox_foreground" time="0.000"/>
	<testcase classname="CheckOpiFormat" name="test_GIVEN_plot_area_THEN_it_has_correct_background_colour" time="0.000"/>
	<testcase classname="CheckOpiFormat" name="test_GIVEN_a_label_THEN_it_ends_in_a_colon" time="0.000">
		<error message="Label on line 2081 with text 'Current Value' did not end in a colon.
Label on line 2122 with text 'Set New Value' did not end in a colon." type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "check_opi_format.py", line 93, in test_GIVEN_a_label_THEN_it_ends_in_a_colon
    self.fail(message)
AssertionError: Label on line 2081 with text 'Current Value' did not end in a colon.
Label on line 2122 with text 'Set New Value' did not end in a colon.
]]>		</error>
	</testcase>
	<testcase classname="CheckOpiFormat" name="test_GIVEN_a_label_within_a_grouping_container_THEN_it_is_sentence_case" time="0.000">
		<error message="Label on line 587 with text 'Heater Vout:' is not sentence case
Label on line 2081 with text 'Current Value' is not sentence case
Label on line 2122 with text 'Set New Value' is not sentence case" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "check_opi_format.py", line 100, in test_GIVEN_a_label_within_a_grouping_container_THEN_it_is_sentence_case
    self.fail(message)
AssertionError: Label on line 587 with text 'Heater Vout:' is not sentence case
Label on line 2081 with text 'Current Value' is not sentence case
Label on line 2122 with text 'Set New Value' is not sentence case
]]>		</error>
	</testcase>
	<testcase classname="CheckOpiFormat" name="test_GIVEN_an_opi_file_with_grouping_containers_WHEN_checking_the_background_colour_THEN_it_is_the_isis_background" time="0.016">
		<error message="On line 61, text 'Grouping Container', colour was not correct.
On line 1481, text 'Configure', colour was not correct." type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "check_opi_format.py", line 68, in test_GIVEN_an_opi_file_with_grouping_containers_WHEN_checking_the_background_colour_THEN_it_is_the_isis_background
    self._assert_colour_correct("background_color", "groupingContainer", ["ISIS_OPI_Background"])
  File "check_opi_format.py", line 58, in _assert_colour_correct
    self.fail("\n".join(["On line {}, text '{}', colour was not correct.".format(*error) for error in errors]))
AssertionError: On line 61, text 'Grouping Container', colour was not correct.
On line 1481, text 'Configure', colour was not correct.
]]>		</error>
	</testcase>
	<testcase classname="CheckOpiFormat" name="test_GIVEN_an_opi_file_with_led_WHEN_checking_off_colour_THEN_it_is_the_isis_led_off_colour" time="0.000">
		<error message="On line 878, text 'ramp_led', colour was not correct." type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "check_opi_format.py", line 83, in test_GIVEN_an_opi_file_with_led_WHEN_checking_off_colour_THEN_it_is_the_isis_led_off_colour
    self._assert_colour_correct("off_color", "LED", ["ISIS_Green_LED_Off", "ISIS_Red_LED_Off"])
  File "check_opi_format.py", line 58, in _assert_colour_correct
    self.fail("\n".join(["On line {}, text '{}', colour was not correct.".format(*error) for error in errors]))
AssertionError: On line 878, text 'ramp_led', colour was not correct.
]]>		</error>
	</testcase>
	<testcase classname="CheckOpiFormat" name="test_GIVEN_an_opi_file_with_led_WHEN_checking_on_colour_THEN_it_is_the_isis_led_on_colour" time="0.000">
		<error message="On line 845, text 'ramp_led', colour was not correct." type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "check_opi_format.py", line 80, in test_GIVEN_an_opi_file_with_led_WHEN_checking_on_colour_THEN_it_is_the_isis_led_on_colour
    self._assert_colour_correct("on_color", "LED", ["ISIS_Green_LED_On", "ISIS_Red_LED_On"])
  File "check_opi_format.py", line 58, in _assert_colour_correct
    self.fail("\n".join(["On line {}, text '{}', colour was not correct.".format(*error) for error in errors]))
AssertionError: On line 845, text 'ramp_led', colour was not correct.
]]>		</error>
	</testcase>
	<system-out>
<![CDATA[]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
